### ISSUE TITLE
Change Shortcut or disable

### ISSUE THREAD

**Issue by davidcolo** [dbilgili/GoogleTranslate#9]
Please can you enable the "disable shortcut" function or at least make it customizable? 
CMD + G conflicts with other Adobe commands. 
Thank you!

**Comment by dbilgili** [comment]
Hey,
If you right click on the menubar icon you will see the `Use CMD+G shortcut` option to toggle it.

**Comment by davidcolo** [comment]
Thank you!
By doing Ctrl + click (setting that I use for the right button), nothing appeared, enabling the right "classic" button the menu appears.
Thank you!

**Comment by dbilgili** [comment]
Apparently you ran into an edge case. I will fix this in the next version 👍🏻

**Comment by davidcolo** [comment]
Thank you! 👏🏼
